"""One connection layer for every store: SQLite on this machine, Postgres in the cloud.

Set `DATABASE_URL` (Supabase's pooled connection string) and every storage
module talks to Postgres; leave it empty and they keep using the SQLite files
under `app/data` exactly as before, which is also what the test-suite does.

The modules keep writing SQLite-flavoured SQL with `?` placeholders. When the
backend is Postgres this layer rewrites the handful of dialect differences on
the way through (`?` → `%s`, `AUTOINCREMENT`, `BLOB`, case-insensitive `LIKE`,
`COLLATE NOCASE`, `PRAGMA`) so the 190-odd statements in the stores did not
have to be rewritten twice.
"""
from __future__ import annotations

import atexit
import os
import re
import sqlite3
import threading
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Callable, Iterator, Mapping, Sequence

Row = Mapping[str, Any]
Init = Callable[["Connection"], None]

_pool = None
_pool_lock = threading.Lock()
_initialized: set[str] = set()
_init_lock = threading.Lock()


def database_url() -> str:
    return os.getenv("DATABASE_URL", "").strip()


def using_postgres() -> bool:
    return bool(database_url())


def backend_name() -> str:
    return "postgres" if using_postgres() else "sqlite"


# --------------------------------------------------------------- translation

_QUOTED = re.compile(r"'(?:[^']|'')*'")
_RULES = (
    (re.compile(r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b", re.IGNORECASE),
     "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
    (re.compile(r"\bBLOB\b", re.IGNORECASE), "BYTEA"),
    (re.compile(r"\bREAL\b", re.IGNORECASE), "DOUBLE PRECISION"),
    # SQLite LIKE ignores ASCII case; Postgres needs ILIKE for the same result.
    (re.compile(r"(?<![A-Za-z_])LIKE\b", re.IGNORECASE), "ILIKE"),
    (re.compile(r"\b([A-Za-z_][A-Za-z0-9_.]*)\s+COLLATE\s+NOCASE\b", re.IGNORECASE), r"lower(\1)"),
)


def translate(sql: str, *, has_params: bool) -> str:
    """SQLite-flavoured SQL as Postgres accepts it. Quoted literals are left alone
    apart from doubling `%`, which psycopg would otherwise read as a placeholder."""
    out: list[str] = []
    last = 0
    for match in _QUOTED.finditer(sql):
        out.append(_translate_code(sql[last:match.start()]))
        literal = match.group(0)
        out.append(literal.replace("%", "%%") if has_params else literal)
        last = match.end()
    out.append(_translate_code(sql[last:]))
    return "".join(out)


def _translate_code(fragment: str) -> str:
    fragment = fragment.replace("?", "%s")
    for pattern, replacement in _RULES:
        fragment = pattern.sub(replacement, fragment)
    return fragment


def is_pragma(sql: str) -> bool:
    return sql.lstrip().upper().startswith("PRAGMA")


def transaction_control(sql: str) -> str | None:
    """'begin' | 'commit' | 'rollback' for SQLite's explicit transaction statements, else None.

    psycopg opens a transaction on the first statement and the stores commit
    through the connection, so `BEGIN IMMEDIATE` (SQLite's "take the write lock
    now") has nothing to do on Postgres.
    """
    words = sql.strip().rstrip(";").upper().split()
    if not words:
        return None
    if words[0] == "BEGIN":
        return "begin"
    if words[0] in ("COMMIT", "END"):
        return "commit"
    if words[0] == "ROLLBACK" and "TO" not in words:
        return "rollback"
    return None


def _normalize_params(params: Sequence[Any] | Mapping[str, Any] | None) -> Any:
    if params is None:
        return None
    if isinstance(params, Mapping):
        return {k: (int(v) if isinstance(v, bool) else v) for k, v in params.items()}
    # The stores keep flags in INTEGER columns; Postgres refuses a Python bool there.
    return tuple(int(v) if isinstance(v, bool) else v for v in params)


class _EmptyCursor:
    rowcount = 0

    def fetchone(self) -> None:
        return None

    def fetchall(self) -> list:
        return []

    def __iter__(self) -> Iterator:
        return iter(())


# --------------------------------------------------------------- connection

class Connection:
    """The subset of the DB-API the stores use, identical on both backends."""

    def __init__(self, raw: Any, dialect: str) -> None:
        self.raw = raw
        self.dialect = dialect

    def execute(self, sql: str, params: Sequence[Any] | Mapping[str, Any] | None = None) -> Any:
        if self.dialect == "sqlite":
            return self.raw.execute(sql, params if params is not None else ())
        if is_pragma(sql):
            return _EmptyCursor()
        control = transaction_control(sql)
        if control is not None:
            if control == "commit":
                self.raw.commit()
            elif control == "rollback":
                self.raw.rollback()
            return _EmptyCursor()
        normalized = _normalize_params(params)
        has_params = normalized is not None and len(normalized) > 0
        return self.raw.execute(translate(sql, has_params=has_params), normalized if has_params else None)

    def executemany(self, sql: str, rows: Sequence[Sequence[Any]]) -> None:
        if self.dialect == "sqlite":
            self.raw.executemany(sql, rows)
            return
        with self.raw.cursor() as cursor:
            cursor.executemany(translate(sql, has_params=True), [_normalize_params(row) for row in rows])

    def commit(self) -> None:
        self.raw.commit()

    def rollback(self) -> None:
        self.raw.rollback()


def _open_sqlite(path: Path) -> sqlite3.Connection:
    path.parent.mkdir(parents=True, exist_ok=True)
    raw = sqlite3.connect(path)
    raw.row_factory = sqlite3.Row
    raw.execute("PRAGMA foreign_keys = ON")
    return raw


def _postgres_pool():
    global _pool
    if _pool is None:
        with _pool_lock:
            if _pool is None:
                from psycopg.rows import dict_row
                from psycopg_pool import ConnectionPool

                _pool = ConnectionPool(
                    conninfo=database_url(),
                    min_size=1,
                    max_size=max(2, int(os.getenv("DATABASE_POOL_SIZE", "8") or 8)),
                    # Supabase's transaction pooler cannot hold server-side
                    # prepared statements between requests.
                    kwargs={"row_factory": dict_row, "prepare_threshold": None},
                    open=True,
                )
    return _pool


def _run_init_once(key: str, init: Init | None, conn: Connection) -> None:
    """Schema DDL runs once per process against Postgres; SQLite re-checks every time (cheap, and tests swap files)."""
    if init is None:
        return
    if conn.dialect == "sqlite":
        init(conn)
        return
    # Nine stores share researchmind.sqlite3, so the memo must be per init function, not per file.
    key = f"{key}:{getattr(init, '__module__', '')}.{getattr(init, '__qualname__', repr(init))}"
    if key in _initialized:
        return
    with _init_lock:
        if key not in _initialized:
            init(conn)
            conn.commit()
            _initialized.add(key)


@contextmanager
def connect(path: Path, init: Init | None = None) -> Iterator[Connection]:
    """`with db.connect(DB_PATH, init_db) as conn:` — commits on success, rolls back on error.

    `path` is the SQLite file; under Postgres it only names the schema group
    for the one-time init, since all stores share one database.
    """
    if using_postgres():
        with _postgres_pool().connection() as raw:
            conn = Connection(raw, "postgres")
            _run_init_once(path.name, init, conn)
            yield conn
        return

    raw = _open_sqlite(path)
    conn = Connection(raw, "sqlite")
    try:
        if init is not None:
            init(conn)
        yield conn
        raw.commit()
    except BaseException:
        raw.rollback()
        raise
    finally:
        raw.close()


# --------------------------------------------------------------- introspection

def table_columns(conn: Connection, table: str) -> set[str]:
    if conn.dialect == "sqlite":
        return {row[1] for row in conn.raw.execute(f"PRAGMA table_info({table})").fetchall()}
    rows = conn.raw.execute(
        "SELECT column_name FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = %s",
        (table,),
    ).fetchall()
    return {row["column_name"] for row in rows}


def table_names(conn: Connection) -> set[str]:
    if conn.dialect == "sqlite":
        return {row[0] for row in conn.raw.execute("SELECT name FROM sqlite_master WHERE type = 'table'").fetchall()}
    rows = conn.raw.execute(
        "SELECT table_name FROM information_schema.tables WHERE table_schema = current_schema() AND table_type = 'BASE TABLE'"
    ).fetchall()
    return {row["table_name"] for row in rows}


def reset_identity(conn: Connection, table: str, column: str = "id") -> None:
    """After bulk-loading rows with explicit ids, move the identity sequence past them."""
    if conn.dialect != "postgres":
        return
    conn.raw.execute(
        f"SELECT setval(pg_get_serial_sequence('{table}', '{column}'), COALESCE((SELECT MAX({column}) FROM {table}), 0) + 1, false)"
    )


def close() -> None:
    """Close the Postgres pool (scripts call this before exiting)."""
    global _pool
    if _pool is not None:
        try:
            _pool.close()
        except Exception:
            pass
        _pool = None


def reset_for_tests() -> None:
    """Forget the one-time init memo and drop the pool (test isolation)."""
    _initialized.clear()
    close()


# uvicorn and one-off scripts both exit through here; without it psycopg's
# pool workers are still running at interpreter shutdown and complain.
atexit.register(close)
