"""The SQLite→Postgres translation layer, tested without a Postgres."""

from __future__ import annotations

import sqlite3

from app.storage import db


def test_placeholders_and_dialect_keywords_are_rewritten():
    sql = """
        CREATE TABLE IF NOT EXISTS t (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            data BLOB NOT NULL,
            score REAL,
            name TEXT
        )
    """
    out = db.translate(sql, has_params=False)
    assert "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in out
    assert "BYTEA" in out and "BLOB" not in out
    assert "DOUBLE PRECISION" in out and " REAL" not in out


def test_question_marks_inside_string_literals_survive():
    out = db.translate("SELECT * FROM t WHERE a = ? AND b = 'what?' AND c = 'it''s ?'", has_params=True)
    assert out == "SELECT * FROM t WHERE a = %s AND b = 'what?' AND c = 'it''s ?'"


def test_percent_in_literals_is_escaped_only_when_params_are_sent():
    sql = "SELECT * FROM t WHERE name LIKE '%' || ? || '%'"
    assert db.translate(sql, has_params=True) == "SELECT * FROM t WHERE name ILIKE '%%' || %s || '%%'"
    assert db.translate("SELECT '100%'", has_params=False) == "SELECT '100%'"


def test_like_and_collate_nocase_keep_sqlite_case_insensitivity():
    assert db.translate("WHERE title LIKE ? OR body LIKE ?", has_params=True) == "WHERE title ILIKE %s OR body ILIKE %s"
    assert db.translate("ORDER BY name COLLATE NOCASE", has_params=False) == "ORDER BY lower(name)"
    # UNLIKE / ILIKE are not touched twice.
    assert db.translate("WHERE x ILIKE ?", has_params=True) == "WHERE x ILIKE %s"


def test_pragmas_become_no_ops_on_postgres():
    assert db.is_pragma("  PRAGMA foreign_keys = ON")
    cursor = db._EmptyCursor()
    assert cursor.fetchall() == [] and cursor.fetchone() is None and list(cursor) == []


def test_sqlite_transaction_statements_are_recognised():
    assert db.transaction_control("BEGIN IMMEDIATE") == "begin"
    assert db.transaction_control("  begin transaction; ") == "begin"
    assert db.transaction_control("COMMIT") == "commit" and db.transaction_control("END") == "commit"
    assert db.transaction_control("ROLLBACK") == "rollback"
    assert db.transaction_control("ROLLBACK TO SAVEPOINT s") is None  # not a whole-transaction rollback
    assert db.transaction_control("SELECT 1") is None and db.transaction_control("") is None


def test_bool_params_become_integers():
    assert db._normalize_params((True, False, 3, "x", None)) == (1, 0, 3, "x", None)
    assert db._normalize_params({"a": True}) == {"a": 1}
    assert db._normalize_params(None) is None


def test_backend_follows_database_url(monkeypatch):
    monkeypatch.delenv("DATABASE_URL", raising=False)
    assert db.backend_name() == "sqlite" and not db.using_postgres()
    monkeypatch.setenv("DATABASE_URL", "postgresql://u:p@h/db")
    assert db.backend_name() == "postgres" and db.using_postgres()


def test_sqlite_connect_runs_init_commits_and_rolls_back(tmp_path, monkeypatch):
    monkeypatch.delenv("DATABASE_URL", raising=False)
    path = tmp_path / "t.sqlite3"
    inits = []

    def init(conn):
        inits.append(1)
        conn.execute("CREATE TABLE IF NOT EXISTS t (id INTEGER PRIMARY KEY AUTOINCREMENT, v TEXT)")

    with db.connect(path, init) as conn:
        conn.execute("INSERT INTO t (v) VALUES (?)", ("a",))
        assert conn.dialect == "sqlite"
        assert db.table_columns(conn, "t") == {"id", "v"}
        assert "t" in db.table_names(conn)
    try:
        with db.connect(path, init) as conn:
            conn.execute("INSERT INTO t (v) VALUES (?)", ("b",))
            raise RuntimeError("boom")
    except RuntimeError:
        pass
    raw = sqlite3.connect(path)
    assert [row[0] for row in raw.execute("SELECT v FROM t ORDER BY id")] == ["a"]
    raw.close()
    assert len(inits) == 2  # SQLite re-checks the schema on every connection
