import { useCallback, useEffect, useRef, useState } from 'react';
import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, BarChart3, Bell, Check, CheckCheck, ChevronLeft, ChevronRight, CircleDollarSign, ExternalLink, Gauge, Info, ListFilter, LogOut, Menu, RefreshCw, Search, Settings2, ShieldCheck, SlidersHorizontal, Users, X, TriangleAlert } from 'lucide-react';
import { ApiError, dashboard, download, exportCalls, request, supabase } from './api';
import { csv, dateTime, duration, money, number, relative } from './format';
import { demoDashboard, filteredDemo, resolveDemo } from './demo';
import { ModelChart, SpendChart } from './charts';
import { Budget, CallsTable, colors, Empty, Loading, Metric, Panel } from './ui';
import { Inspector } from './Inspector';
import { Settings } from './Settings';
import type { Dashboard, Filters, Identity, Issue, Page } from './types';

const navigation = [
  { id: 'overview', label: 'Overview', icon: Gauge }, { id: 'costs', label: 'Cost explorer', icon: CircleDollarSign },
  { id: 'calls', label: 'Calls & traces', icon: Activity }, { id: 'issues', label: 'Issues', icon: TriangleAlert }, { id: 'users', label: 'Users', icon: Users },
] as const;
const defaultFilters: Filters = { kind: '', status: '', query: '', user_id: '', model: '' };
function currentPage(): Page { const hash = window.location.hash.slice(1); return [...navigation.map(n => n.id), 'settings'].includes(hash) ? hash as Page : 'overview'; }

export function App({ demo, identity }: { demo: boolean; identity: Identity }) {
  const [page, setPage] = useState<Page>(currentPage);
  const [days, setDays] = useState(7);
  const [search, setSearch] = useState('');
  const [filters, setFilters] = useState<Filters>(defaultFilters);
  const [offset, setOffset] = useState(0);
  const [data, setData] = useState<Dashboard | null>(null);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const [auto, setAuto] = useState(true);
  const [refresh, setRefresh] = useState(0);
  const [selected, setSelected] = useState<string | null>(null);
  const [mobileNav, setMobileNav] = useState(false);
  const [toast, setToast] = useState('');
  const [exporting, setExporting] = useState(false);
  const [showResolved, setShowResolved] = useState(false);
  const toastTimer = useRef<ReturnType<typeof setTimeout>>();
  const notify = useCallback((message: string) => { setToast(message); clearTimeout(toastTimer.current); toastTimer.current = setTimeout(() => setToast(''), 5000); }, []);
  const reload = useCallback(() => setRefresh(r => r + 1), []);
  const closeInspector = useCallback(() => setSelected(null), []);

  useEffect(() => {
    const onHash = () => setPage(currentPage());
    window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash);
  }, []);
  useEffect(() => { window.location.hash = page; setMobileNav(false); document.title = `${page === 'settings' ? 'Settings' : navigation.find(n => n.id === page)?.label} · Research Ops`; }, [page]);
  useEffect(() => {
    const timer = setTimeout(() => { setFilters(f => ({ ...f, query: search })); setOffset(0); if (search) setPage('calls'); }, 250);
    return () => clearTimeout(timer);
  }, [search]);
  useEffect(() => {
    if (!auto || demo) return;
    const timer = setInterval(() => { if (document.visibilityState === 'visible') reload(); }, 15000);
    const visible = () => { if (document.visibilityState === 'visible') reload(); };
    document.addEventListener('visibilitychange', visible);
    return () => { clearInterval(timer); document.removeEventListener('visibilitychange', visible); };
  }, [auto, demo, reload]);
  useEffect(() => {
    let active = true; setLoading(true);
    if (demo) { setData(demoDashboard(days, filters, offset)); setError(''); setLoading(false); return; }
    void dashboard(days, filters, offset).then(next => { if (active) { setData(next); setError(''); } }).catch(e => { if (active) setError(e instanceof Error ? e.message : 'Could not load activity.'); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [days, filters, offset, refresh, demo]);
  useEffect(() => () => clearTimeout(toastTimer.current), []);
  useEffect(() => { setOffset(0); }, [days]);

  function navigate(next: Page) { setPage(next); setSearch(''); setFilters(defaultFilters); setOffset(0); }
  function filter(next: Partial<Filters>) { setFilters(f => ({ ...f, ...next })); setOffset(0); }
  function viewModel(model: string) { setPage('calls'); setSearch(''); setFilters({ ...defaultFilters, kind: 'llm', model }); setOffset(0); }
  function viewUser(user_id: string) { setPage('calls'); setSearch(''); setFilters({ ...defaultFilters, user_id }); setOffset(0); }
  async function exportData() {
    setExporting(true);
    try {
      if (demo) { const rows = filteredDemo(days, filters); download(new Blob([csv(rows as unknown as Record<string, unknown>[], ['id', 'request_id', 'kind', 'name', 'model', 'user_email', 'status', 'duration_ms', 'input_tokens', 'output_tokens', 'cost_usd'])], { type: 'text/csv' }), 'sample-research-ops-calls.csv'); notify(`Exported ${rows.length} sample calls.`); }
      else { const total = await exportCalls(days, filters); notify(total > 10000 ? 'Exported the latest 10,000 calls. Narrow your filters to export the remaining calls.' : `Exported ${total} calls.`); }
    } catch (e) { notify(e instanceof Error ? e.message : 'Export failed.'); }
    finally { setExporting(false); }
  }
  async function resolve(issue: Issue) {
    try {
      if (demo) resolveDemo(issue.fingerprint, !issue.resolved);
      else await request(`/ops/issues/${issue.fingerprint}`, { method: 'PATCH', body: JSON.stringify({ resolved: !issue.resolved }) });
      notify(issue.resolved ? 'Issue reopened.' : 'Issue marked resolved. A new failure will reopen it.'); reload();
    } catch (e) { notify(e instanceof Error ? e.message : 'Could not update issue.'); }
  }

  const overview = data?.overview;
  const openIssues = data?.issues.filter(i => !i.resolved) ?? [];
  const currentNav = navigation.find(n => n.id === page);
  const heading = { overview: ['Your research, at a glance.', 'A little less noise. A clear view of what’s happening.'], costs: ['Every token, accounted for.', 'Understand your spend across models and research workflows.'], calls: ['Follow every call.', 'See what was called, who called it, and what happened next.'], issues: ['Catch the unexpected.', 'A focused view of failures that need your attention.'], users: ['Know your workspace.', 'Understand who’s using your application and what it costs.'], settings: ['Make it your own.', 'Set your budget, model rates, and monitoring sources.'] }[page];
  const budgetAlert = overview && overview.monthly.cost >= overview.settings.monthly_budget * overview.settings.alert_percent / 100;

  return <div className="app-shell">
    {mobileNav && <div className="nav-backdrop" onClick={() => setMobileNav(false)} />}
    <aside className={`sidebar ${mobileNav ? 'mobile-open' : ''}`}><a href="#overview" className="brand" onClick={() => navigate('overview')}><span className="brand-symbol"><BarChart3 size={23} /></span><span><b>research<span>ops</span></b><small>BY ZOETROPE</small></span></a>
      <div className="workspace-card"><span className="workspace-avatar">Z</span><div><b>Research chatbot</b><span><i />{demo ? 'Sample workspace' : 'Your workspace'}</span></div><ShieldCheck size={15} /></div>
      <div className="nav-label">MONITOR</div><nav aria-label="Main navigation">{navigation.map(n => <button key={n.id} className={`nav-item ${page === n.id ? 'active' : ''}`} onClick={() => navigate(n.id)} aria-current={page === n.id ? 'page' : undefined}><n.icon size={18} /><span>{n.label}</span>{n.id === 'issues' && openIssues.length > 0 && <b className="nav-count">{openIssues.length}</b>}</button>)}</nav>
      <div className="nav-label workspace-label">WORKSPACE</div><button className={`nav-item ${page === 'settings' ? 'active' : ''}`} onClick={() => navigate('settings')}><Settings2 size={18} /><span>Settings</span></button><a className="nav-item" href="http://127.0.0.1:5173/app" target="_blank" rel="noreferrer"><ArrowUpRight size={18} /><span>Open chatbot</span><ExternalLink size={12} /></a>
      <div className="sidebar-bottom"><div className="sidebar-note"><span className="sidebar-note-icon"><Activity size={19} /></span><b>The bigger picture.<br />Without the clutter.</b><p>Your research stack, observed.</p><button onClick={() => navigate('settings')}>Monitoring details <ArrowRight size={13} /></button></div><div className="sidebar-user"><span className="avatar">{identity.email[0]?.toUpperCase() || 'A'}</span><div><b>{demo ? 'Preview workspace' : identity.email || 'Local developer'}</b><small>{demo ? 'Sample data' : 'Administrator'}</small></div>{!demo && supabase && <button className="icon-button" aria-label="Sign out" onClick={() => void supabase?.auth.signOut()}><LogOut size={15} /></button>}</div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setMobileNav(true)}><Menu size={20} /></button><span>Workspace</span><ChevronRight size={13} /><b>{currentNav?.label || 'Settings'}</b></div><div className="topbar-right"><label className="global-search"><Search size={15} /><input aria-label="Search calls, models, users" placeholder="Search calls, models, users…" value={search} onChange={e => setSearch(e.target.value)} />{search && <button aria-label="Clear search" onClick={() => setSearch('')}><X size={13} /></button>}</label><span className={`live-badge ${error ? 'disconnected' : ''}`}><i />{demo ? 'Preview' : error ? 'Disconnected' : data?.connection.telemetry_enabled ? 'Live' : loading ? 'Connecting' : 'Paused'}</span><button className={`notification-button ${openIssues.length ? 'has-notifications' : ''}`} aria-label={`${openIssues.length} open issues`} onClick={() => navigate('issues')}><Bell size={18} /></button></div></header>
      {demo && <div className="demo-banner"><Info size={15} /><span><b>Sample data mode.</b> Explore the dashboard with example activity. No live requests are made.</span><a href={window.location.pathname}>Connect workspace <ArrowRight size={13} /></a></div>}
      <main className="content"><div className="page-heading"><div><div className="eyebrow">RESEARCH WORKSPACE <span>/</span> {page === 'overview' ? 'OVERVIEW' : currentNav?.label.toUpperCase() || 'SETTINGS'}</div><h1>{heading[0]}</h1><p>{heading[1]}</p></div>{page !== 'settings' && <div className="page-actions"><label className="period-selector"><span className="sr-only">Time period</span><select aria-label="Time period" value={days} onChange={e => setDays(Number(e.target.value))}><option value={1}>Today</option><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></label><button className="button secondary" disabled={exporting || !data} onClick={() => void exportData()}><ArrowDownToLine size={15} /><span>{exporting ? 'Exporting…' : 'Export'}</span></button></div>}</div>
        <div className="refresh-line"><span><i className={`connection-dot ${!error && data ? 'connected' : ''}`} />{demo ? 'Example activity · not connected to your API' : error ? 'Connection interrupted' : overview ? `Updated ${relative(overview.generated_at).toLowerCase()}` : 'Waiting for your workspace'}<span className="utc-note">· UTC reporting</span></span><div><label className="refresh-toggle"><input type="checkbox" checked={auto} disabled={demo} onChange={e => setAuto(e.target.checked)} /><i />Auto refresh</label><button className="icon-button" aria-label="Refresh dashboard" onClick={reload} disabled={loading}><RefreshCw size={14} className={loading ? 'spin' : ''} /></button></div></div>
        {error && <div className="notice error-notice" role="alert"><TriangleAlert size={16} /><span>{error}{data && ' Showing the last successful snapshot.'}</span><button className="text-button" onClick={reload}>Retry</button>{!data && <a className="text-button" href="?demo=1">Explore sample data</a>}</div>}
        {budgetAlert && page !== 'settings' && <div className="notice budget-notice"><TriangleAlert size={16} /><span>Monthly spend has reached {Math.round(overview!.monthly.cost / overview!.settings.monthly_budget * 100)}% of your budget. {money(overview!.monthly.cost)} estimated so far.</span><button className="text-button" onClick={() => navigate('settings')}>Manage budget</button></div>}
        {!data ? loading ? <Loading /> : <Empty title="Waiting for a connection">Start or restart your research chatbot backend, then refresh this dashboard.</Empty> : <>
          {(page === 'overview' || page === 'costs') && <div className="metrics-grid"><Metric label="Estimated spend" value={money(overview!.stats.cost)} icon={CircleDollarSign} current={overview!.stats.cost} before={overview!.previous.cost} note={overview!.previous.cost > 0 ? 'vs. previous period' : 'in this period'} spark={overview!.series.map(s => s.cost)} /><Metric label="Model calls" value={number(overview!.stats.calls)} icon={Activity} current={overview!.stats.calls} before={overview!.previous.calls} note={overview!.previous.calls > 0 ? 'vs. previous period' : `${number(overview!.stats.requests)} requests`} spark={overview!.series.map(s => s.calls)} tone="blue" /><Metric label={page === 'costs' ? 'Average call cost' : 'Failed operations'} value={page === 'costs' ? overview!.stats.calls > overview!.stats.unpriced ? money(overview!.stats.cost / (overview!.stats.calls - overview!.stats.unpriced), true) : '—' : number(overview!.stats.errors)} icon={page === 'costs' ? SlidersHorizontal : TriangleAlert} note={page === 'costs' ? 'priced calls only' : `${openIssues.length} open issues`} spark={overview!.series.map(s => s.errors)} tone="amber" /><Metric label={page === 'costs' ? 'Input + output tokens' : 'Active users'} value={page === 'costs' ? number(overview!.stats.input_tokens + overview!.stats.output_tokens) : number(overview!.stats.users)} icon={page === 'costs' ? BarChart3 : Users} note={page === 'costs' ? `${number(overview!.stats.cached_tokens)} cached input` : 'users seen in this period'} spark={overview!.series.map(s => s.events)} tone="purple" /></div>}
          {page === 'overview' && <><div className="charts-grid"><SpendChart overview={overview!} days={days} /><ModelChart overview={overview!} onModel={viewModel} /></div><div className="activity-grid"><Panel title="Recent activity" caption="A closer look at what’s happening" action={<button className="text-button" onClick={() => navigate('calls')}>View all calls <ArrowRight size={14} /></button>}>{data.events.events.length ? <CallsTable events={data.events.events.slice(0, 6)} onSelect={setSelected} compact /> : <Empty title="Nothing recorded yet">Restart the backend, then use the chatbot. Your next request will appear here.</Empty>}</Panel><div className="attention-column"><Budget metrics={overview!.monthly} budget={overview!.settings.monthly_budget} threshold={overview!.settings.alert_percent} onEdit={() => navigate('settings')} /><Panel title="Needs attention" action={<span className="small-count">{openIssues.length}</span>}><div className="attention-list">{openIssues.length ? openIssues.slice(0, 2).map(i => <button key={i.fingerprint} onClick={() => setSelected(i.event_id)}><span className="attention-icon"><TriangleAlert size={15} /></span><span><b>{i.error_type || 'Request failure'}</b><small>{i.occurrences} occurrences · {i.name}</small></span><ChevronRight size={14} /></button>) : <div className="all-good"><CheckCheck size={20} /><div><b>All clear</b><small>No failures in this period.</small></div></div>}{overview!.stats.unpriced > 0 && <button onClick={() => navigate('settings')}><span className="attention-icon amber"><CircleDollarSign size={15} /></span><span><b>{overview!.stats.unpriced} calls with unknown cost</b><small>Check model pricing and usage</small></span><ChevronRight size={14} /></button>}</div></Panel></div></div><div className="page-footnote"><ShieldCheck size={13} />Only administrators can view workspace telemetry.<span>{number(overview!.stats.events)} recorded operations in this period</span></div></>}
          {page === 'costs' && <><div className="cost-chart-grid"><SpendChart overview={overview!} days={days} large /><Budget metrics={overview!.monthly} budget={overview!.settings.monthly_budget} threshold={overview!.settings.alert_percent} onEdit={() => navigate('settings')} /></div><Panel title="Model breakdown" caption="Compare usage, latency, and spend" action={<button className="text-button" onClick={() => navigate('settings')}>Edit pricing <ArrowRight size={14} /></button>}>{overview!.models.length ? <div className="table-scroll"><table className="breakdown-table"><thead><tr><th>Model</th><th>Calls</th><th>Input tokens</th><th>Output tokens</th><th>Avg. duration</th><th>Est. spend</th><th>Share</th></tr></thead><tbody>{overview!.models.map((m, i) => <tr key={m.provider + m.model}><td><button className="model-link" onClick={() => viewModel(m.model)}><i className="model-dot" style={{ background: colors[i % colors.length] }} /><span><b>{m.model}</b><small>{m.provider}{m.unpriced > 0 ? ` · ${m.unpriced} unpriced` : ''}</small></span></button></td><td>{number(m.calls)}</td><td className="mono">{number(m.input_tokens)}</td><td className="mono">{number(m.output_tokens)}</td><td className="mono">{duration(m.latency_ms)}</td><td className="mono spend-value">{m.calls === m.unpriced ? '—' : money(m.cost, true)}</td><td><div className="share-cell"><span>{overview!.stats.cost > 0 ? `${(m.cost / overview!.stats.cost * 100).toFixed(0)}%` : '—'}</span><div className="progress"><i style={{ width: `${overview!.stats.cost > 0 ? m.cost / overview!.stats.cost * 100 : 0}%`, background: colors[i % colors.length] }} /></div></div></td></tr>)}</tbody></table></div> : <Empty title="No model costs yet">Your first model call will appear in this breakdown.</Empty>}</Panel><Panel title="Research workflows" caption="Request volume and failures by endpoint">{overview!.areas.length ? <div className="workflow-grid">{overview!.areas.map(a => <button key={a.name} onClick={() => { setPage('calls'); setSearch(a.name); filter({ kind: 'http' }); }}><span className="kind-icon">↗</span><div><b>{a.name}</b><small>{number(a.events)} requests · {a.errors} failures</small></div><ArrowRight size={16} /></button>)}</div> : <Empty title="No request activity yet">Workflows appear when the application receives requests.</Empty>}</Panel><p className="field-help">Estimates include recorded LLM calls only. Unknown costs and uninstrumented provider services are excluded. Historical estimates use the rates captured at the time of each call.</p></>}
          {page === 'calls' && <Panel title="Call log" caption={`${number(data.events.total)} matching operations`} action={<span className="table-live"><i />{demo ? 'Sample data' : auto ? 'Updates every 15s' : 'Refresh paused'}</span>}><div className="filters"><ListFilter size={16} /><select aria-label="Operation type" value={filters.kind} onChange={e => filter({ kind: e.target.value })}><option value="">All operations</option><option value="llm">Model calls</option><option value="http">API requests</option><option value="websocket">Assistant connections</option><option value="tool">Agent tools</option><option value="retrieval">Retrieval</option></select><select aria-label="Call status" value={filters.status} onChange={e => filter({ status: e.target.value })}><option value="">All statuses</option><option value="success">Success</option><option value="error">Failed</option><option value="running">Running</option><option value="cancelled">Cancelled</option></select><select aria-label="Model filter" value={filters.model} onChange={e => filter({ model: e.target.value })}><option value="">All models</option>{overview!.models.map(m => <option key={m.provider + m.model} value={m.model}>{m.model}</option>)}</select><select aria-label="User filter" value={filters.user_id} onChange={e => filter({ user_id: e.target.value })}><option value="">All users</option>{data.users.map(u => <option key={u.user_id} value={u.user_id}>{u.email || u.user_id}</option>)}</select>{Object.values(filters).some(Boolean) && <button className="text-button" onClick={() => { setFilters(defaultFilters); setSearch(''); setOffset(0); }}>Clear filters <X size={13} /></button>}</div><div aria-busy={loading}>{data.events.events.length ? <CallsTable events={data.events.events} onSelect={setSelected} /> : <Empty title="No matching calls">{Object.values(filters).some(Boolean) ? 'Try widening the time period or clearing your filters.' : 'Use the chatbot to start recording activity. New calls will appear automatically.'}</Empty>}</div><div className="pagination"><span>{data.events.total ? `${offset + 1}–${Math.min(offset + 25, data.events.total)} of ${number(data.events.total)} calls` : '0 calls'}<small>Unknown costs shown as —</small></span><div><button className="button secondary" disabled={offset === 0 || loading} onClick={() => setOffset(o => Math.max(0, o - 25))}><ChevronLeft size={14} />Previous</button><button className="button secondary" disabled={offset + 25 >= data.events.total || loading} onClick={() => setOffset(o => o + 25)}>Next<ChevronRight size={14} /></button></div></div></Panel>}
          {page === 'issues' && <><div className="issue-summary"><div><span className="issue-summary-icon"><TriangleAlert size={22} /></span><strong>{openIssues.length}</strong><span>open issues</span></div><p>Repeated failures are grouped by operation and error type.<br />Resolved issues reopen when a new failure occurs.</p><label className="checkbox-label"><input type="checkbox" checked={showResolved} onChange={e => setShowResolved(e.target.checked)} />Show resolved</label></div><div className="issues-list">{(showResolved ? data.issues : openIssues).length ? (showResolved ? data.issues : openIssues).map(i => <article className={`issue-card ${i.resolved ? 'resolved' : ''}`} key={i.fingerprint}><div className="issue-icon">{i.resolved ? <Check size={19} /> : <TriangleAlert size={19} />}</div><div className="issue-content"><div><h2>{i.error_type || 'Request failure'}</h2><span className={`status ${i.resolved ? 'status-success' : 'status-error'}`}><i />{i.resolved ? 'Resolved' : 'Open'}</span></div><code>{i.name}</code><p>{i.error || 'The operation failed without an error message.'}</p><div className="issue-meta"><span>{i.occurrences} occurrences</span><span>{i.users} affected users</span><span>Last seen {relative(i.last_seen)}</span></div></div><div className="issue-actions"><button className="button secondary" onClick={() => setSelected(i.event_id)}>Inspect call <ArrowUpRight size={14} /></button><button className="text-button" onClick={() => void resolve(i)}>{i.resolved ? 'Reopen issue' : 'Mark resolved'}<Check size={14} /></button></div></article>) : <Panel title="Workspace issues"><Empty title="All clear for now">No {showResolved ? '' : 'open '}issues in this period. Any failures will appear here with the call that caused them.</Empty></Panel>}</div></>}
          {page === 'users' && <><div className="users-heading"><div><Users size={19} /><b>{data.users.length} active users</b><span>in this period</span></div><span>Activity is attributed to authenticated requests.</span></div><Panel title="User activity" caption="A simple picture of usage and cost">{data.users.length ? <div className="table-scroll"><table className="users-table"><thead><tr><th>User</th><th>Requests</th><th>Model calls</th><th>Failed ops</th><th>Est. spend</th><th>Last seen</th><th /></tr></thead><tbody>{data.users.map((u, i) => <tr key={u.user_id}><td><button className="user-name" onClick={() => viewUser(u.user_id)}><span className={`avatar avatar-${i % 4}`}>{(u.email || u.user_id)[0].toUpperCase()}</span><span><b>{u.email || u.user_id}</b><small>{u.user_id}</small></span></button></td><td>{number(u.requests)}</td><td>{number(u.calls)}</td><td><span className={u.errors ? 'error-count' : ''}>{u.errors}</span></td><td className="mono"><b>{money(u.cost, true)}</b>{u.unpriced > 0 && <small className="cell-note">+ {u.unpriced} unpriced</small>}</td><td className="time-cell">{relative(u.last_seen)}</td><td><button className="icon-button" aria-label={`View calls for ${u.email || u.user_id}`} onClick={() => viewUser(u.user_id)}><ArrowRight size={16} /></button></td></tr>)}</tbody></table></div> : <Empty title="No users recorded yet">Users appear when they make authenticated requests. Background jobs and older imports may be unattributed.</Empty>}</Panel><div className="notice neutral-notice"><Info size={16} /><span>This shows users observed in telemetry. Users with no activity, account registration, and billing subscriptions are outside this view.</span></div></>}
          {page === 'settings' && <Settings value={overview!.settings} connection={data.connection} demo={demo} onSave={reload} notify={notify} />}
        </>}
      </main><footer className="app-footer"><span><BarChart3 size={12} />Research Ops <span>by Zoetrope</span></span><span>Clarity behind every call.</span></footer>
    </div>{selected && <Inspector id={selected} demo={demo} refresh={refresh} onClose={closeInspector} onSelect={setSelected} />}{toast && <div className="toast" role="status"><Check size={17} />{toast}<button className="icon-button" aria-label="Dismiss notification" onClick={() => setToast('')}><X size={15} /></button></div>}
  </div>;
}
